version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/test_db?sslmode=disable
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/test_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy


  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/test_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
