// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type User struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	FirstName      string    `json:"first_name"`
	SecondName     string    `json:"second_name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
